site_name: "Kanji Study Assistant Documentation"

nav:
  - Setup:
    - neo4j: requirements.md
  - References: references.md

plugins:
  - search
  - macros
  # - inline-svg

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

repo_url: https://github.com/weshouman/msc-kanji-study
repo_name: weshouman/msc-kanji-study

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-square

# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
